name: Build Image

on:
  push:
    branches:
      - main

jobs:
  build-amd64:
    name: amd64 image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          ref: "${{ inputs.ref }}"

      - name: Login to registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          push: true
          provenance: false
          context: "{{defaultContext}}"
          tags: "ghcr.io/bradenrayhorn/mise:building-block-amd64-${{ github.sha }}"
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/bradenrayhorn/mise:buildcache-amd64
          cache-to: type=registry,ref=ghcr.io/bradenrayhorn/mise:buildcache-amd64,mode=max

  build-arm64:
    name: arm64 image
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          ref: "${{ inputs.ref }}"

      - name: Login to registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          push: true
          provenance: false
          context: "{{defaultContext}}"
          tags: "ghcr.io/bradenrayhorn/mise:building-block-arm64-${{ github.sha }}"
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/bradenrayhorn/mise:buildcache-arm64
          cache-to: type=registry,ref=ghcr.io/bradenrayhorn/mise:buildcache-arm64,mode=max

  retag-next:
    name: Push multiarch image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [build-arm64, build-amd64]
    steps:
      - name: Login to registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Retag
        run: |
          IMAGE=ghcr.io/bradenrayhorn/mise

          docker buildx imagetools create \
            --tag $IMAGE:next \
            --tag $IMAGE:next-${{ github.sha }} \
            $IMAGE:building-block-amd64-${{ github.sha }} \
            $IMAGE:building-block-arm64-${{ github.sha }}
